project:
  type: book
  output-dir: docs

book:
  title: "Charting Inequality: A Deep Dive into Chicago's Poverty Landscape"
  author: "Gregory Ho"
  date: "03/05/2024"
  chapters:
    - index.qmd
    - multidimensional_poverty.qmd
    
format:
  html:
    theme: cosmo
    toc: true
    navbar:
      left:
        - text: "Home"
          href: index.qmd
        - text: "Methodology"
          href: multidimensional_poverty.qmd
  pdf:
    documentclass: scrreprt

editor: visual

