project:
  type: book
  output-dir: docs

book:
  title: "Charting Inequality: A Deep Dive into Chicago's Poverty Landscape"
  author: "Gregory Ho"
  date: "03/05/2024"
  chapters:
    - index.qmd
    - spatial_distribution.qmd
    - digital_divide_analysis.qmd
    - multidimensional_poverty.qmd
    - credits.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    navbar:
      left:
        - text: "Home"
          href: index.qmd
        - text: "Spatial Distribution"
          href: spatial_distribution.qmd
        - text: "Digital Divide Analysis"
          href: digital_divide_analysis.qmd
        - text: "Methodology"
          href: multidimensional_poverty.qmd
        - text: "Credits"
          href: credits.qmd
  pdf:
    documentclass: scrreprt

editor: visual